# Generated by Django 3.1.4 on 2020-12-27 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50, verbose_name='Кабинет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_begin', models.DateTimeField(verbose_name='Начало брони')),
                ('booking_end', models.DateTimeField(verbose_name='Конец брони')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.workplace')),
            ],
        ),
    ]
