# Generated by Django 3.1.4 on 2020-12-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201227_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(blank=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(blank=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='created_at',
            field=models.DateTimeField(blank=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='updated_at',
            field=models.DateTimeField(blank=True, verbose_name='Дата обновления'),
        ),
    ]
